[package]
name = "vulkan-particles"
version = "0.1.0"
authors = ["Michael Noser <michael@noser.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
